### ISSUE TITLE
Please add ionic logo

### ISSUE THREAD

**Issue by luckylooke** [VectorLogoZone/vlz-contrib#1]
I am not sure how to contribute and add [ionic](https://ionicframework.com/) logo. Thanks :)

**Comment by dan5382** [comment]
No problem! Let us know if it gets accepted. 
https://github.com/VectorLogoZone/vlz-contrib

**Comment by fileformat** [comment]
[Added](https://www.vectorlogo.zone/logos/ionicframework/index.html), thanks!
