### ISSUE TITLE
Discord.js logo

### ISSUE THREAD

**Issue by PieterSpruijt** [VectorLogoZone/vlz-contrib#5]
Discord.js is the biggest api library for discord bots! https://discord.js.org or https://discordjs.guide https://discord.gg/djs for the official verified server!
Included the official logos
![images](https://user-images.githubusercontent.com/55944075/130318395-63cc9ce2-1b24-4473-b3d9-e77ab7983c2a.png)
![e305e980-cb80-11eb-9bb9-c5d3ec013658](https://user-images.githubusercontent.com/55944075/130318396-f8ac44f9-3075-4bae-a5f9-223670ae97e9.png)

**Comment by fileformat** [comment]
[Added](https://www.vectorlogo.zone/logos/js_discord/index.html), thanks!
